version: '2'
services:
  risk:
    entrypoint: zsh
    build: docker
    volumes:
      - ./analysis:/src
      - /Volumes/GdH_data/risk_precision/ds-numrisk:/data
      - $FREESURFER_HOME/license.txt:/opt/freesurfer-6.0.0/license.txt
