version: '2'
services:
  risk:
    entrypoint: zsh
    build: .
    volumes:
      - ./analysis:/src
      - ./braincoder:/braincoder
      - /data:/data
      - /Volumes/GdH_data/risk_precision/:/raw
      - $FREESURFER_HOME/license.txt:/opt/freesurfer-6.0.0/license.txt
