#!/bin/sh
#SBATCH --job-name=decode_trialwise
#SBATCH --output=/home/gholland/git/numerosity_risk/fit_model/.out/decode_trialwise.%A.%a.out
#SBATCH --error=/home/gholland/git/numerosity_risk/fit_model/.out/decode_trialwise.%A.%a.error
#SBATCH --time=12:00:00
#SBATCH --partition=gpu

source $HOME/.bashrc
conda activate tf_gpu 
python $HOME/git/numerosity_risk/fit_model/decode.py $SLURM_ARRAY_TASK_ID --sourcedata=$HOME/data/risk_precision/ds-numrisk/ --trialwise
