#!/bin/sh
#SBATCH --job-name=decode_runwise
#SBATCH --output=/home/gholland/git/numerosity_risk/fit_model/.out/decode_runwise.%A.%a.out
#SBATCH --error=/home/gholland/git/numerosity_risk/fit_model/.out/decode_runwise.%A.%a.error
#SBATCH --time=3:00:00
#SBATCH --partition=gpu

source $HOME/.bashrc
conda activate tf_gpu 
python $HOME/git/numerosity_risk/fit_model/decode.py $SLURM_ARRAY_TASK_ID --sourcedata=$HOME/data/risk_precision/ds-numrisk/ --masks NPC1_L NPC2_L NPC3_L NF1_L NF2_L NTO_L NINS_L --unsmoothed
